INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Neville','Shaw','315 Nunc Ave','Idaho Falls','ID','52634');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Carlos','Hess','Apt #430 Convallis St.','San Jose','CA','92300');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Tatiana','Dominguez','8284 A, St.','Baton Rouge','LA','50698');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Bevis','Lawrence','491 Aliquet Ave','Lewiston','ME','47258');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Melodie','Obrien','417 Tortor, Road','Tuscaloosa','AL','36966');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Xenos','Winters','7977 Rutrum Rd.','Atlanta','GA','95337');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Buffy','Wells','3322 Sit Ave','Kapolei','HI','32338');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Danielle','Ewing','Apt #757 Pede. Road','Cedar Rapids','IA','27781');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Quincy','Berg','983 Nunc St.','Provo','UT','26006');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Orla','Blanchard','Apt #785 Pellentesque Avenue','Lowell','MA','88724');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kaden','Ware','6476 Nulla. St.','Nampa','ID','79581');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Isabella','Hogan','Apt #955 Elit, Road','Topeka','KS','27056');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Hanna','England','1804 Diam Av.','Phoenix','AZ','85521');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Thane','Jordan','2946 Nibh. Street','Springfield','MO','27483');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Zoe','Cruz','8218 Phasellus Road','Biloxi','MS','74916');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Amela','Pickett','7625 Mauris. Rd.','San Antonio','TX','31102');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Cora','Pratt','Apt #248 Vel, Rd.','South Burlington','VT','31782');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Jana','Pierce','7319 Eu Street','Overland Park','KS','19517');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Hu','Campos','459 Gravida St.','Baltimore','MD','53946');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Acton','Blake','616 Diam Ave','Newport News','VA','81894');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Griffith','Salazar','3685 Malesuada Ave','Broken Arrow','OK','46573');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kareem','Drake','Apt #195 Ornare, Rd.','Wichita','KS','32852');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Carter','Mcfadden','9498 Tellus, Rd.','San Jose','CA','95642');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Chadwick','Head','731 Placerat, St.','Annapolis','MD','86722');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Griffin','Salazar','4545 Molestie Rd.','Evansville','IN','18000');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Adria','Miranda','206 Semper Street','Madison','WI','96402');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Dante','Moon','5206 Rutrum. Rd.','Honolulu','HI','18366');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kyra','Humphrey','123 Blandit Rd.','Olympia','WA','91586');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Sopoline','Patton','852 Quis Av.','Fort Collins','CO','63120');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Tiger','Mckenzie','Apt #949 Taciti Rd.','Rockville','MD','20241');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Lydia','Ayers','6221 Ridiculus Ave','Evansville','IN','46657');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Garrett','Woods','Apt #732 Porttitor Avenue','Saint Louis','MO','90262');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Nigel','Franco','3964 Justo Rd.','Green Bay','WI','25172');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Mohammad','Gould','Apt #674 Tempus St.','Des Moines','IA','43938');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Jacqueline','Little','6563 Aliquam Av.','Kenosha','WI','79177');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Ursa','Scott','3247 Euismod Rd.','New Haven','CT','69685');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Holly','Charles','1879 Donec St.','Knoxville','TN','12529');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Ashton','Christensen','Apt #166 Nulla Avenue','San Jose','CA','94109');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Martha','Farrell','8246 Tincidunt, Ave','Carson City','NV','26725');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Colby','Kelly','Apt #151 Sed Rd.','Green Bay','WI','93889');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Blake','Carter','6371 Iaculis Street','Boston','MA','52740');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kaye','Preston','Apt #790 Nisi. Avenue','Columbia','MO','79810');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kylynn','Riddle','4298 Diam. St.','Allentown','PA','81462');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Alisa','Morton','601 Erat St.','Columbia','MD','52423');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Dane','Bailey','867 Ut Rd.','Norfolk','VA','65070');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Caldwell','Forbes','Apt #487 Aliquet Road','Rockville','MD','15488');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kenyon','Webb','4765 Vel, Av.','Philadelphia','PA','95650');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Brielle','Fitzgerald','670 Lacus. Ave','Columbia','MD','74938');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kristen','Brewer','Apt #681 Malesuada Avenue','Seattle','WA','13257');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Lila','Reilly','Apt #878 Et Avenue','Houston','TX','59459');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Aquila','Elliott','3865 Augue Avenue','Lakewood','CO','72149');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Amal','Pena','1279 Malesuada Av.','Wilmington','DE','45500');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Salvador','Rocha','Apt #505 Sit Rd.','Springfield','MA','66663');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Tucker','Paul','Apt #762 Porttitor Rd.','Grand Island','NE','77335');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Veda','Love','646 Ac Road','Houston','TX','68497');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Sarah','Henson','4848 Nunc, Rd.','Houston','TX','94283');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Aiko','Reid','612 Ipsum Road','Lakewood','CO','93664');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Joy','Luna','Apt #247 Est, Street','College','AK','99632');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Daquan','Barry','899 Consectetuer Rd.','South Portland','ME','95375');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Yael','Richardson','2627 Sit Rd.','Montpelier','VT','46324');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Larissa','Richardson','Apt #798 Justo St.','Nashville','TN','99447');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Harrison','Gilmore','3624 Ornare. Road','Savannah','GA','63907');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Brett','Melton','640 Vestibulum Street','Joliet','IL','24927');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Ferdinand','Castillo','Apt #660 Pede. Rd.','Salem','OR','93269');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Hedley','Crosby','4784 Eget, St.','Idaho Falls','ID','18265');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Sylvia','Garza','722 Pede, Street','Cambridge','MA','81515');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Jescie','Slater','6842 Cursus, Av.','Bear','DE','52054');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Acton','Bentley','4657 Scelerisque St.','Rock Springs','WY','83211');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Katelyn','Cummings','862 Magna. Street','Sterling Heights','MI','99937');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('September','Sexton','542 Nunc Street','Gulfport','MS','67927');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Shellie','Wyatt','213 Et Ave','San Diego','CA','91609');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Tyler','Drake','7274 Amet, Street','Grand Rapids','MI','86720');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Aidan','Fowler','897 Varius Avenue','Springdale','AR','71472');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('McKenzie','Levine','Apt #656 Odio Rd.','Columbia','MD','29914');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Aaron','Terrell','Apt #546 Parturient Rd.','Mesa','AZ','86153');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Drake','Kirby','4834 Id Av.','Billings','MT','34430');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Susan','Harrison','5568 In St.','Huntsville','AL','36475');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Geoffrey','Morrow','4019 Mauris Street','Southaven','MS','70546');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Xena','Paul','Apt #939 Pede Rd.','Tulsa','OK','97659');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Nissim','Dale','6128 Luctus Av.','Hilo','HI','46731');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Vincent','Keller','853 Egestas Av.','San Antonio','TX','81878');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Ivan','Ferguson','1781 Risus Av.','Allentown','PA','42269');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Stacey','Burris','116 Aliquet. Road','Flint','MI','25136');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Quincy','Malone','7671 Ipsum St.','Grand Island','NE','66273');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Ashton','Patrick','8598 Euismod Rd.','Atlanta','GA','40111');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Amela','Daniel','731 Urna St.','College','AK','99614');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Isaac','Tyson','295 Diam. Avenue','Provo','UT','12877');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Paula','Ashley','7144 Tempor Rd.','Rockville','MD','25186');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Stella','Lang','Apt #329 Aliquet St.','Auburn','ME','64792');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Yael','Burch','676 Lorem. Avenue','Great Falls','MT','85181');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Gretchen','Banks','2458 Accumsan Av.','Ketchikan','AK','99822');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Jordan','Goff','7106 Elit, Avenue','Kailua','HI','91557');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Colorado','Mccullough','7837 Euismod Av.','Grand Island','NE','43959');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Kimberly','Mclaughlin','1848 Est. Ave','North Las Vegas','NV','31052');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Sylvester','Foley','7109 Purus. Avenue','Wilmington','DE','10788');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Erin','Bernard','Apt #6209 Enim. St.','Gresham','OR','25194');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Gareth','Carlson','6177 Eu Street','San Diego','CA','96767');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Stephen','Gamble','9856 Interdum St.','Joliet','IL','71321');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Wendy','Hammond','Apt #654 Tempus, Road','Rochester','MN','92300');
INSERT INTO customer (first_name,last_name,street,city,state,zip) VALUES ('Allistair','Talley','Apt #4030 Fusce Av.','Philadelphia','PA','75098');
