insert into product (part_number, color, brand, category, name) values (538012, 'Black', 'Amana', 'Dishwasher', 'Black Amana Dishwasher');
insert into product (part_number, color, brand, category, name) values (854754, 'Black', 'Amana', 'Dryer', 'Black Amana Dryer');
insert into product (part_number, color, brand, category, name) values (698436, 'Black', 'Amana', 'Electric Range', 'Black Amana Electric Range');
insert into product (part_number, color, brand, category, name) values (484062, 'Black', 'Amana', 'Freezer', 'Black Amana Freezer');
insert into product (part_number, color, brand, category, name) values (827996, 'Black', 'Amana', 'Gas Range', 'Black Amana Gas Range');
insert into product (part_number, color, brand, category, name) values (630874, 'Black', 'Amana', 'Microwave', 'Black Amana Microwave');
insert into product (part_number, color, brand, category, name) values (621784, 'Black', 'Amana', 'Refrigerator', 'Black Amana Refrigerator');
insert into product (part_number, color, brand, category, name) values (134805, 'Black', 'Amana', 'Washer', 'Black Amana Washer');
insert into product (part_number, color, brand, category, name) values (775009, 'Black', 'Bosch', 'Dishwasher', 'Black Bosch Dishwasher');
insert into product (part_number, color, brand, category, name) values (381145, 'Black', 'Bosch', 'Dryer', 'Black Bosch Dryer');
insert into product (part_number, color, brand, category, name) values (625787, 'Black', 'Bosch', 'Electric Range', 'Black Bosch Electric Range');
insert into product (part_number, color, brand, category, name) values (765387, 'Black', 'Bosch', 'Freezer', 'Black Bosch Freezer');
insert into product (part_number, color, brand, category, name) values (784680, 'Black', 'Bosch', 'Gas Range', 'Black Bosch Gas Range');
insert into product (part_number, color, brand, category, name) values (841410, 'Black', 'Bosch', 'Microwave', 'Black Bosch Microwave');
insert into product (part_number, color, brand, category, name) values (509107, 'Black', 'Bosch', 'Refrigerator', 'Black Bosch Refrigerator');
insert into product (part_number, color, brand, category, name) values (894405, 'Black', 'Bosch', 'Washer', 'Black Bosch Washer');
insert into product (part_number, color, brand, category, name) values (958154, 'Black', 'Danby', 'Dishwasher', 'Black Danby Dishwasher');
insert into product (part_number, color, brand, category, name) values (392318, 'Black', 'Danby', 'Dryer', 'Black Danby Dryer');
insert into product (part_number, color, brand, category, name) values (551782, 'Black', 'Danby', 'Electric Range', 'Black Danby Electric Range');
insert into product (part_number, color, brand, category, name) values (567760, 'Black', 'Danby', 'Freezer', 'Black Danby Freezer');
insert into product (part_number, color, brand, category, name) values (540103, 'Black', 'Danby', 'Gas Range', 'Black Danby Gas Range');
insert into product (part_number, color, brand, category, name) values (457786, 'Black', 'Danby', 'Microwave', 'Black Danby Microwave');
insert into product (part_number, color, brand, category, name) values (962025, 'Black', 'Danby', 'Refrigerator', 'Black Danby Refrigerator');
insert into product (part_number, color, brand, category, name) values (718661, 'Black', 'Danby', 'Washer', 'Black Danby Washer');
insert into product (part_number, color, brand, category, name) values (133458, 'Black', 'Fagor', 'Dishwasher', 'Black Fagor Dishwasher');
insert into product (part_number, color, brand, category, name) values (870494, 'Black', 'Fagor', 'Dryer', 'Black Fagor Dryer');
insert into product (part_number, color, brand, category, name) values (548579, 'Black', 'Fagor', 'Electric Range', 'Black Fagor Electric Range');
insert into product (part_number, color, brand, category, name) values (398439, 'Black', 'Fagor', 'Freezer', 'Black Fagor Freezer');
insert into product (part_number, color, brand, category, name) values (307997, 'Black', 'Fagor', 'Gas Range', 'Black Fagor Gas Range');
insert into product (part_number, color, brand, category, name) values (584915, 'Black', 'Fagor', 'Microwave', 'Black Fagor Microwave');
insert into product (part_number, color, brand, category, name) values (852724, 'Black', 'Fagor', 'Refrigerator', 'Black Fagor Refrigerator');
insert into product (part_number, color, brand, category, name) values (505160, 'Black', 'Fagor', 'Washer', 'Black Fagor Washer');
insert into product (part_number, color, brand, category, name) values (703215, 'Black', 'Frigidaire', 'Dishwasher', 'Black Frigidaire Dishwasher');
insert into product (part_number, color, brand, category, name) values (649723, 'Black', 'Frigidaire', 'Dryer', 'Black Frigidaire Dryer');
insert into product (part_number, color, brand, category, name) values (308040, 'Black', 'Frigidaire', 'Electric Range', 'Black Frigidaire Electric Range');
insert into product (part_number, color, brand, category, name) values (155065, 'Black', 'Frigidaire', 'Freezer', 'Black Frigidaire Freezer');
insert into product (part_number, color, brand, category, name) values (703010, 'Black', 'Frigidaire', 'Gas Range', 'Black Frigidaire Gas Range');
insert into product (part_number, color, brand, category, name) values (972297, 'Black', 'Frigidaire', 'Microwave', 'Black Frigidaire Microwave');
insert into product (part_number, color, brand, category, name) values (804484, 'Black', 'Frigidaire', 'Refrigerator', 'Black Frigidaire Refrigerator');
insert into product (part_number, color, brand, category, name) values (124602, 'Black', 'Frigidaire', 'Washer', 'Black Frigidaire Washer');
insert into product (part_number, color, brand, category, name) values (753227, 'Black', 'GE', 'Dishwasher', 'Black GE Dishwasher');
insert into product (part_number, color, brand, category, name) values (340442, 'Black', 'GE', 'Dryer', 'Black GE Dryer');
insert into product (part_number, color, brand, category, name) values (222514, 'Black', 'GE', 'Electric Range', 'Black GE Electric Range');
insert into product (part_number, color, brand, category, name) values (731237, 'Black', 'GE', 'Freezer', 'Black GE Freezer');
insert into product (part_number, color, brand, category, name) values (867521, 'Black', 'GE', 'Gas Range', 'Black GE Gas Range');
insert into product (part_number, color, brand, category, name) values (892120, 'Black', 'GE', 'Microwave', 'Black GE Microwave');
insert into product (part_number, color, brand, category, name) values (752138, 'Black', 'GE', 'Refrigerator', 'Black GE Refrigerator');
insert into product (part_number, color, brand, category, name) values (670730, 'Black', 'GE', 'Washer', 'Black GE Washer');
insert into product (part_number, color, brand, category, name) values (132654, 'Black', 'Haier', 'Dishwasher', 'Black Haier Dishwasher');
insert into product (part_number, color, brand, category, name) values (726126, 'Black', 'Haier', 'Dryer', 'Black Haier Dryer');
insert into product (part_number, color, brand, category, name) values (205291, 'Black', 'Haier', 'Electric Range', 'Black Haier Electric Range');
insert into product (part_number, color, brand, category, name) values (255243, 'Black', 'Haier', 'Freezer', 'Black Haier Freezer');
insert into product (part_number, color, brand, category, name) values (892917, 'Black', 'Haier', 'Gas Range', 'Black Haier Gas Range');
insert into product (part_number, color, brand, category, name) values (232722, 'Black', 'Haier', 'Microwave', 'Black Haier Microwave');
insert into product (part_number, color, brand, category, name) values (803355, 'Black', 'Haier', 'Refrigerator', 'Black Haier Refrigerator');
insert into product (part_number, color, brand, category, name) values (568288, 'Black', 'Haier', 'Washer', 'Black Haier Washer');
insert into product (part_number, color, brand, category, name) values (133969, 'Black', 'Hotpoint', 'Dishwasher', 'Black Hotpoint Dishwasher');
insert into product (part_number, color, brand, category, name) values (232674, 'Black', 'Hotpoint', 'Dryer', 'Black Hotpoint Dryer');
insert into product (part_number, color, brand, category, name) values (792163, 'Black', 'Hotpoint', 'Electric Range', 'Black Hotpoint Electric Range');
insert into product (part_number, color, brand, category, name) values (837281, 'Black', 'Hotpoint', 'Freezer', 'Black Hotpoint Freezer');
insert into product (part_number, color, brand, category, name) values (942244, 'Black', 'Hotpoint', 'Gas Range', 'Black Hotpoint Gas Range');
insert into product (part_number, color, brand, category, name) values (619627, 'Black', 'Hotpoint', 'Microwave', 'Black Hotpoint Microwave');
insert into product (part_number, color, brand, category, name) values (537542, 'Black', 'Hotpoint', 'Refrigerator', 'Black Hotpoint Refrigerator');
insert into product (part_number, color, brand, category, name) values (300179, 'Black', 'Hotpoint', 'Washer', 'Black Hotpoint Washer');
insert into product (part_number, color, brand, category, name) values (939218, 'Black', 'LG', 'Dishwasher', 'Black LG Dishwasher');
insert into product (part_number, color, brand, category, name) values (716666, 'Black', 'LG', 'Dryer', 'Black LG Dryer');
insert into product (part_number, color, brand, category, name) values (314838, 'Black', 'LG', 'Electric Range', 'Black LG Electric Range');
insert into product (part_number, color, brand, category, name) values (443865, 'Black', 'LG', 'Freezer', 'Black LG Freezer');
insert into product (part_number, color, brand, category, name) values (632273, 'Black', 'LG', 'Gas Range', 'Black LG Gas Range');
insert into product (part_number, color, brand, category, name) values (795338, 'Black', 'LG', 'Microwave', 'Black LG Microwave');
insert into product (part_number, color, brand, category, name) values (589672, 'Black', 'LG', 'Refrigerator', 'Black LG Refrigerator');
insert into product (part_number, color, brand, category, name) values (642745, 'Black', 'LG', 'Washer', 'Black LG Washer');
insert into product (part_number, color, brand, category, name) values (242614, 'Black', 'Miele', 'Dishwasher', 'Black Miele Dishwasher');
insert into product (part_number, color, brand, category, name) values (673386, 'Black', 'Miele', 'Dryer', 'Black Miele Dryer');
insert into product (part_number, color, brand, category, name) values (892469, 'Black', 'Miele', 'Electric Range', 'Black Miele Electric Range');
insert into product (part_number, color, brand, category, name) values (140363, 'Black', 'Miele', 'Freezer', 'Black Miele Freezer');
insert into product (part_number, color, brand, category, name) values (825785, 'Black', 'Miele', 'Gas Range', 'Black Miele Gas Range');
insert into product (part_number, color, brand, category, name) values (343364, 'Black', 'Miele', 'Microwave', 'Black Miele Microwave');
insert into product (part_number, color, brand, category, name) values (357727, 'Black', 'Miele', 'Refrigerator', 'Black Miele Refrigerator');
insert into product (part_number, color, brand, category, name) values (641695, 'Black', 'Miele', 'Washer', 'Black Miele Washer');
insert into product (part_number, color, brand, category, name) values (621227, 'Black', 'Samsung', 'Dishwasher', 'Black Samsung Dishwasher');
insert into product (part_number, color, brand, category, name) values (918912, 'Black', 'Samsung', 'Dryer', 'Black Samsung Dryer');
insert into product (part_number, color, brand, category, name) values (138922, 'Black', 'Samsung', 'Electric Range', 'Black Samsung Electric Range');
insert into product (part_number, color, brand, category, name) values (412459, 'Black', 'Samsung', 'Freezer', 'Black Samsung Freezer');
insert into product (part_number, color, brand, category, name) values (475171, 'Black', 'Samsung', 'Gas Range', 'Black Samsung Gas Range');
insert into product (part_number, color, brand, category, name) values (781273, 'Black', 'Samsung', 'Microwave', 'Black Samsung Microwave');
insert into product (part_number, color, brand, category, name) values (736148, 'Black', 'Samsung', 'Refrigerator', 'Black Samsung Refrigerator');
insert into product (part_number, color, brand, category, name) values (225964, 'Black', 'Samsung', 'Washer', 'Black Samsung Washer');
insert into product (part_number, color, brand, category, name) values (632451, 'Black', 'Subzero', 'Dishwasher', 'Black Subzero Dishwasher');
insert into product (part_number, color, brand, category, name) values (325217, 'Black', 'Subzero', 'Dryer', 'Black Subzero Dryer');
insert into product (part_number, color, brand, category, name) values (232388, 'Black', 'Subzero', 'Electric Range', 'Black Subzero Electric Range');
insert into product (part_number, color, brand, category, name) values (248817, 'Black', 'Subzero', 'Freezer', 'Black Subzero Freezer');
insert into product (part_number, color, brand, category, name) values (966990, 'Black', 'Subzero', 'Gas Range', 'Black Subzero Gas Range');
insert into product (part_number, color, brand, category, name) values (565057, 'Black', 'Subzero', 'Microwave', 'Black Subzero Microwave');
insert into product (part_number, color, brand, category, name) values (244056, 'Black', 'Subzero', 'Refrigerator', 'Black Subzero Refrigerator');
insert into product (part_number, color, brand, category, name) values (620094, 'Black', 'Subzero', 'Washer', 'Black Subzero Washer');
insert into product (part_number, color, brand, category, name) values (196786, 'White', 'Amana', 'Dishwasher', 'White Amana Dishwasher');
insert into product (part_number, color, brand, category, name) values (690432, 'White', 'Amana', 'Dryer', 'White Amana Dryer');
insert into product (part_number, color, brand, category, name) values (753549, 'White', 'Amana', 'Electric Range', 'White Amana Electric Range');
insert into product (part_number, color, brand, category, name) values (698717, 'White', 'Amana', 'Freezer', 'White Amana Freezer');
insert into product (part_number, color, brand, category, name) values (655886, 'White', 'Amana', 'Gas Range', 'White Amana Gas Range');
insert into product (part_number, color, brand, category, name) values (409953, 'White', 'Amana', 'Microwave', 'White Amana Microwave');
insert into product (part_number, color, brand, category, name) values (392504, 'White', 'Amana', 'Refrigerator', 'White Amana Refrigerator');
insert into product (part_number, color, brand, category, name) values (927377, 'White', 'Amana', 'Washer', 'White Amana Washer');
insert into product (part_number, color, brand, category, name) values (662666, 'White', 'Bosch', 'Dishwasher', 'White Bosch Dishwasher');
insert into product (part_number, color, brand, category, name) values (454923, 'White', 'Bosch', 'Dryer', 'White Bosch Dryer');
insert into product (part_number, color, brand, category, name) values (225790, 'White', 'Bosch', 'Electric Range', 'White Bosch Electric Range');
insert into product (part_number, color, brand, category, name) values (870788, 'White', 'Bosch', 'Freezer', 'White Bosch Freezer');
insert into product (part_number, color, brand, category, name) values (210352, 'White', 'Bosch', 'Gas Range', 'White Bosch Gas Range');
insert into product (part_number, color, brand, category, name) values (608064, 'White', 'Bosch', 'Microwave', 'White Bosch Microwave');
insert into product (part_number, color, brand, category, name) values (875243, 'White', 'Bosch', 'Refrigerator', 'White Bosch Refrigerator');
insert into product (part_number, color, brand, category, name) values (750917, 'White', 'Bosch', 'Washer', 'White Bosch Washer');
insert into product (part_number, color, brand, category, name) values (413107, 'White', 'Danby', 'Dishwasher', 'White Danby Dishwasher');
insert into product (part_number, color, brand, category, name) values (788004, 'White', 'Danby', 'Dryer', 'White Danby Dryer');
insert into product (part_number, color, brand, category, name) values (463709, 'White', 'Danby', 'Electric Range', 'White Danby Electric Range');
insert into product (part_number, color, brand, category, name) values (851328, 'White', 'Danby', 'Freezer', 'White Danby Freezer');
insert into product (part_number, color, brand, category, name) values (807901, 'White', 'Danby', 'Gas Range', 'White Danby Gas Range');
insert into product (part_number, color, brand, category, name) values (312512, 'White', 'Danby', 'Microwave', 'White Danby Microwave');
insert into product (part_number, color, brand, category, name) values (728007, 'White', 'Danby', 'Refrigerator', 'White Danby Refrigerator');
insert into product (part_number, color, brand, category, name) values (347837, 'White', 'Danby', 'Washer', 'White Danby Washer');
insert into product (part_number, color, brand, category, name) values (400621, 'White', 'Fagor', 'Dishwasher', 'White Fagor Dishwasher');
insert into product (part_number, color, brand, category, name) values (899343, 'White', 'Fagor', 'Dryer', 'White Fagor Dryer');
insert into product (part_number, color, brand, category, name) values (686663, 'White', 'Fagor', 'Electric Range', 'White Fagor Electric Range');
insert into product (part_number, color, brand, category, name) values (935092, 'White', 'Fagor', 'Freezer', 'White Fagor Freezer');
insert into product (part_number, color, brand, category, name) values (295896, 'White', 'Fagor', 'Gas Range', 'White Fagor Gas Range');
insert into product (part_number, color, brand, category, name) values (702689, 'White', 'Fagor', 'Microwave', 'White Fagor Microwave');
insert into product (part_number, color, brand, category, name) values (577320, 'White', 'Fagor', 'Refrigerator', 'White Fagor Refrigerator');
insert into product (part_number, color, brand, category, name) values (733681, 'White', 'Fagor', 'Washer', 'White Fagor Washer');
insert into product (part_number, color, brand, category, name) values (770093, 'White', 'Frigidaire', 'Dishwasher', 'White Frigidaire Dishwasher');
insert into product (part_number, color, brand, category, name) values (705491, 'White', 'Frigidaire', 'Dryer', 'White Frigidaire Dryer');
insert into product (part_number, color, brand, category, name) values (607698, 'White', 'Frigidaire', 'Electric Range', 'White Frigidaire Electric Range');
insert into product (part_number, color, brand, category, name) values (574140, 'White', 'Frigidaire', 'Freezer', 'White Frigidaire Freezer');
insert into product (part_number, color, brand, category, name) values (266909, 'White', 'Frigidaire', 'Gas Range', 'White Frigidaire Gas Range');
insert into product (part_number, color, brand, category, name) values (865790, 'White', 'Frigidaire', 'Microwave', 'White Frigidaire Microwave');
insert into product (part_number, color, brand, category, name) values (310941, 'White', 'Frigidaire', 'Refrigerator', 'White Frigidaire Refrigerator');
insert into product (part_number, color, brand, category, name) values (556181, 'White', 'Frigidaire', 'Washer', 'White Frigidaire Washer');
insert into product (part_number, color, brand, category, name) values (239743, 'White', 'GE', 'Dishwasher', 'White GE Dishwasher');
insert into product (part_number, color, brand, category, name) values (323715, 'White', 'GE', 'Dryer', 'White GE Dryer');
insert into product (part_number, color, brand, category, name) values (396650, 'White', 'GE', 'Electric Range', 'White GE Electric Range');
insert into product (part_number, color, brand, category, name) values (637936, 'White', 'GE', 'Freezer', 'White GE Freezer');
insert into product (part_number, color, brand, category, name) values (904700, 'White', 'GE', 'Gas Range', 'White GE Gas Range');
insert into product (part_number, color, brand, category, name) values (575685, 'White', 'GE', 'Microwave', 'White GE Microwave');
insert into product (part_number, color, brand, category, name) values (153028, 'White', 'GE', 'Refrigerator', 'White GE Refrigerator');
insert into product (part_number, color, brand, category, name) values (878211, 'White', 'GE', 'Washer', 'White GE Washer');
insert into product (part_number, color, brand, category, name) values (599106, 'White', 'Haier', 'Dishwasher', 'White Haier Dishwasher');
insert into product (part_number, color, brand, category, name) values (236277, 'White', 'Haier', 'Dryer', 'White Haier Dryer');
insert into product (part_number, color, brand, category, name) values (189189, 'White', 'Haier', 'Electric Range', 'White Haier Electric Range');
insert into product (part_number, color, brand, category, name) values (422677, 'White', 'Haier', 'Freezer', 'White Haier Freezer');
insert into product (part_number, color, brand, category, name) values (406098, 'White', 'Haier', 'Gas Range', 'White Haier Gas Range');
insert into product (part_number, color, brand, category, name) values (158216, 'White', 'Haier', 'Microwave', 'White Haier Microwave');
insert into product (part_number, color, brand, category, name) values (959299, 'White', 'Haier', 'Refrigerator', 'White Haier Refrigerator');
insert into product (part_number, color, brand, category, name) values (793466, 'White', 'Haier', 'Washer', 'White Haier Washer');
insert into product (part_number, color, brand, category, name) values (149464, 'White', 'Hotpoint', 'Dishwasher', 'White Hotpoint Dishwasher');
insert into product (part_number, color, brand, category, name) values (371355, 'White', 'Hotpoint', 'Dryer', 'White Hotpoint Dryer');
insert into product (part_number, color, brand, category, name) values (400280, 'White', 'Hotpoint', 'Electric Range', 'White Hotpoint Electric Range');
insert into product (part_number, color, brand, category, name) values (642633, 'White', 'Hotpoint', 'Freezer', 'White Hotpoint Freezer');
insert into product (part_number, color, brand, category, name) values (661287, 'White', 'Hotpoint', 'Gas Range', 'White Hotpoint Gas Range');
insert into product (part_number, color, brand, category, name) values (300894, 'White', 'Hotpoint', 'Microwave', 'White Hotpoint Microwave');
insert into product (part_number, color, brand, category, name) values (511214, 'White', 'Hotpoint', 'Refrigerator', 'White Hotpoint Refrigerator');
insert into product (part_number, color, brand, category, name) values (360565, 'White', 'Hotpoint', 'Washer', 'White Hotpoint Washer');
insert into product (part_number, color, brand, category, name) values (202688, 'White', 'LG', 'Dishwasher', 'White LG Dishwasher');
insert into product (part_number, color, brand, category, name) values (125897, 'White', 'LG', 'Dryer', 'White LG Dryer');
insert into product (part_number, color, brand, category, name) values (493410, 'White', 'LG', 'Electric Range', 'White LG Electric Range');
insert into product (part_number, color, brand, category, name) values (533087, 'White', 'LG', 'Freezer', 'White LG Freezer');
insert into product (part_number, color, brand, category, name) values (485515, 'White', 'LG', 'Gas Range', 'White LG Gas Range');
insert into product (part_number, color, brand, category, name) values (613194, 'White', 'LG', 'Microwave', 'White LG Microwave');
insert into product (part_number, color, brand, category, name) values (132754, 'White', 'LG', 'Refrigerator', 'White LG Refrigerator');
insert into product (part_number, color, brand, category, name) values (730390, 'White', 'LG', 'Washer', 'White LG Washer');
insert into product (part_number, color, brand, category, name) values (204275, 'White', 'Miele', 'Dishwasher', 'White Miele Dishwasher');
insert into product (part_number, color, brand, category, name) values (758268, 'White', 'Miele', 'Dryer', 'White Miele Dryer');
insert into product (part_number, color, brand, category, name) values (295371, 'White', 'Miele', 'Electric Range', 'White Miele Electric Range');
insert into product (part_number, color, brand, category, name) values (480886, 'White', 'Miele', 'Freezer', 'White Miele Freezer');
insert into product (part_number, color, brand, category, name) values (188740, 'White', 'Miele', 'Gas Range', 'White Miele Gas Range');
insert into product (part_number, color, brand, category, name) values (218380, 'White', 'Miele', 'Microwave', 'White Miele Microwave');
insert into product (part_number, color, brand, category, name) values (994462, 'White', 'Miele', 'Refrigerator', 'White Miele Refrigerator');
insert into product (part_number, color, brand, category, name) values (881389, 'White', 'Miele', 'Washer', 'White Miele Washer');
insert into product (part_number, color, brand, category, name) values (922935, 'White', 'Samsung', 'Dishwasher', 'White Samsung Dishwasher');
insert into product (part_number, color, brand, category, name) values (621022, 'White', 'Samsung', 'Dryer', 'White Samsung Dryer');
insert into product (part_number, color, brand, category, name) values (912299, 'White', 'Samsung', 'Electric Range', 'White Samsung Electric Range');
insert into product (part_number, color, brand, category, name) values (787621, 'White', 'Samsung', 'Freezer', 'White Samsung Freezer');
insert into product (part_number, color, brand, category, name) values (619801, 'White', 'Samsung', 'Gas Range', 'White Samsung Gas Range');
insert into product (part_number, color, brand, category, name) values (184400, 'White', 'Samsung', 'Microwave', 'White Samsung Microwave');
insert into product (part_number, color, brand, category, name) values (230099, 'White', 'Samsung', 'Refrigerator', 'White Samsung Refrigerator');
insert into product (part_number, color, brand, category, name) values (538977, 'White', 'Samsung', 'Washer', 'White Samsung Washer');
insert into product (part_number, color, brand, category, name) values (780042, 'White', 'Subzero', 'Dishwasher', 'White Subzero Dishwasher');
insert into product (part_number, color, brand, category, name) values (460398, 'White', 'Subzero', 'Dryer', 'White Subzero Dryer');
insert into product (part_number, color, brand, category, name) values (979426, 'White', 'Subzero', 'Electric Range', 'White Subzero Electric Range');
insert into product (part_number, color, brand, category, name) values (304900, 'White', 'Subzero', 'Freezer', 'White Subzero Freezer');
insert into product (part_number, color, brand, category, name) values (907192, 'White', 'Subzero', 'Gas Range', 'White Subzero Gas Range');
insert into product (part_number, color, brand, category, name) values (182922, 'White', 'Subzero', 'Microwave', 'White Subzero Microwave');
insert into product (part_number, color, brand, category, name) values (830203, 'White', 'Subzero', 'Refrigerator', 'White Subzero Refrigerator');
insert into product (part_number, color, brand, category, name) values (615674, 'White', 'Subzero', 'Washer', 'White Subzero Washer');
insert into product (part_number, color, brand, category, name) values (843871, 'Red', 'Amana', 'Dishwasher', 'Red Amana Dishwasher');
insert into product (part_number, color, brand, category, name) values (532764, 'Red', 'Amana', 'Dryer', 'Red Amana Dryer');
insert into product (part_number, color, brand, category, name) values (800585, 'Red', 'Amana', 'Electric Range', 'Red Amana Electric Range');
insert into product (part_number, color, brand, category, name) values (277361, 'Red', 'Amana', 'Freezer', 'Red Amana Freezer');
insert into product (part_number, color, brand, category, name) values (182276, 'Red', 'Amana', 'Gas Range', 'Red Amana Gas Range');
insert into product (part_number, color, brand, category, name) values (293430, 'Red', 'Amana', 'Microwave', 'Red Amana Microwave');
insert into product (part_number, color, brand, category, name) values (512154, 'Red', 'Amana', 'Refrigerator', 'Red Amana Refrigerator');
insert into product (part_number, color, brand, category, name) values (593573, 'Red', 'Amana', 'Washer', 'Red Amana Washer');
insert into product (part_number, color, brand, category, name) values (200032, 'Red', 'Bosch', 'Dishwasher', 'Red Bosch Dishwasher');
insert into product (part_number, color, brand, category, name) values (700797, 'Red', 'Bosch', 'Dryer', 'Red Bosch Dryer');
insert into product (part_number, color, brand, category, name) values (662956, 'Red', 'Bosch', 'Electric Range', 'Red Bosch Electric Range');
insert into product (part_number, color, brand, category, name) values (476535, 'Red', 'Bosch', 'Freezer', 'Red Bosch Freezer');
insert into product (part_number, color, brand, category, name) values (526869, 'Red', 'Bosch', 'Gas Range', 'Red Bosch Gas Range');
insert into product (part_number, color, brand, category, name) values (440525, 'Red', 'Bosch', 'Microwave', 'Red Bosch Microwave');
insert into product (part_number, color, brand, category, name) values (534567, 'Red', 'Bosch', 'Refrigerator', 'Red Bosch Refrigerator');
insert into product (part_number, color, brand, category, name) values (488414, 'Red', 'Bosch', 'Washer', 'Red Bosch Washer');
insert into product (part_number, color, brand, category, name) values (252876, 'Red', 'Danby', 'Dishwasher', 'Red Danby Dishwasher');
insert into product (part_number, color, brand, category, name) values (668682, 'Red', 'Danby', 'Dryer', 'Red Danby Dryer');
insert into product (part_number, color, brand, category, name) values (668936, 'Red', 'Danby', 'Electric Range', 'Red Danby Electric Range');
insert into product (part_number, color, brand, category, name) values (833053, 'Red', 'Danby', 'Freezer', 'Red Danby Freezer');
insert into product (part_number, color, brand, category, name) values (721290, 'Red', 'Danby', 'Gas Range', 'Red Danby Gas Range');
insert into product (part_number, color, brand, category, name) values (205803, 'Red', 'Danby', 'Microwave', 'Red Danby Microwave');
insert into product (part_number, color, brand, category, name) values (818838, 'Red', 'Danby', 'Refrigerator', 'Red Danby Refrigerator');
insert into product (part_number, color, brand, category, name) values (968510, 'Red', 'Danby', 'Washer', 'Red Danby Washer');
insert into product (part_number, color, brand, category, name) values (225711, 'Red', 'Fagor', 'Dishwasher', 'Red Fagor Dishwasher');
insert into product (part_number, color, brand, category, name) values (527285, 'Red', 'Fagor', 'Dryer', 'Red Fagor Dryer');
insert into product (part_number, color, brand, category, name) values (769611, 'Red', 'Fagor', 'Electric Range', 'Red Fagor Electric Range');
insert into product (part_number, color, brand, category, name) values (324172, 'Red', 'Fagor', 'Freezer', 'Red Fagor Freezer');
insert into product (part_number, color, brand, category, name) values (228451, 'Red', 'Fagor', 'Gas Range', 'Red Fagor Gas Range');
insert into product (part_number, color, brand, category, name) values (233577, 'Red', 'Fagor', 'Microwave', 'Red Fagor Microwave');
insert into product (part_number, color, brand, category, name) values (507991, 'Red', 'Fagor', 'Refrigerator', 'Red Fagor Refrigerator');
insert into product (part_number, color, brand, category, name) values (529827, 'Red', 'Fagor', 'Washer', 'Red Fagor Washer');
insert into product (part_number, color, brand, category, name) values (712880, 'Red', 'Frigidaire', 'Dishwasher', 'Red Frigidaire Dishwasher');
insert into product (part_number, color, brand, category, name) values (646974, 'Red', 'Frigidaire', 'Dryer', 'Red Frigidaire Dryer');
insert into product (part_number, color, brand, category, name) values (273763, 'Red', 'Frigidaire', 'Electric Range', 'Red Frigidaire Electric Range');
insert into product (part_number, color, brand, category, name) values (743129, 'Red', 'Frigidaire', 'Freezer', 'Red Frigidaire Freezer');
insert into product (part_number, color, brand, category, name) values (751448, 'Red', 'Frigidaire', 'Gas Range', 'Red Frigidaire Gas Range');
insert into product (part_number, color, brand, category, name) values (858034, 'Red', 'Frigidaire', 'Microwave', 'Red Frigidaire Microwave');
insert into product (part_number, color, brand, category, name) values (523756, 'Red', 'Frigidaire', 'Refrigerator', 'Red Frigidaire Refrigerator');
insert into product (part_number, color, brand, category, name) values (258552, 'Red', 'Frigidaire', 'Washer', 'Red Frigidaire Washer');
insert into product (part_number, color, brand, category, name) values (773351, 'Red', 'GE', 'Dishwasher', 'Red GE Dishwasher');
insert into product (part_number, color, brand, category, name) values (445165, 'Red', 'GE', 'Dryer', 'Red GE Dryer');
insert into product (part_number, color, brand, category, name) values (266929, 'Red', 'GE', 'Electric Range', 'Red GE Electric Range');
insert into product (part_number, color, brand, category, name) values (270493, 'Red', 'GE', 'Freezer', 'Red GE Freezer');
insert into product (part_number, color, brand, category, name) values (118728, 'Red', 'GE', 'Gas Range', 'Red GE Gas Range');
insert into product (part_number, color, brand, category, name) values (571281, 'Red', 'GE', 'Microwave', 'Red GE Microwave');
insert into product (part_number, color, brand, category, name) values (317301, 'Red', 'GE', 'Refrigerator', 'Red GE Refrigerator');
insert into product (part_number, color, brand, category, name) values (916251, 'Red', 'GE', 'Washer', 'Red GE Washer');
insert into product (part_number, color, brand, category, name) values (118086, 'Red', 'Haier', 'Dishwasher', 'Red Haier Dishwasher');
insert into product (part_number, color, brand, category, name) values (397752, 'Red', 'Haier', 'Dryer', 'Red Haier Dryer');
insert into product (part_number, color, brand, category, name) values (255225, 'Red', 'Haier', 'Electric Range', 'Red Haier Electric Range');
insert into product (part_number, color, brand, category, name) values (435023, 'Red', 'Haier', 'Freezer', 'Red Haier Freezer');
insert into product (part_number, color, brand, category, name) values (702158, 'Red', 'Haier', 'Gas Range', 'Red Haier Gas Range');
insert into product (part_number, color, brand, category, name) values (161236, 'Red', 'Haier', 'Microwave', 'Red Haier Microwave');
insert into product (part_number, color, brand, category, name) values (231686, 'Red', 'Haier', 'Refrigerator', 'Red Haier Refrigerator');
insert into product (part_number, color, brand, category, name) values (529739, 'Red', 'Haier', 'Washer', 'Red Haier Washer');
insert into product (part_number, color, brand, category, name) values (379143, 'Red', 'Hotpoint', 'Dishwasher', 'Red Hotpoint Dishwasher');
insert into product (part_number, color, brand, category, name) values (906375, 'Red', 'Hotpoint', 'Dryer', 'Red Hotpoint Dryer');
insert into product (part_number, color, brand, category, name) values (633013, 'Red', 'Hotpoint', 'Electric Range', 'Red Hotpoint Electric Range');
insert into product (part_number, color, brand, category, name) values (317879, 'Red', 'Hotpoint', 'Freezer', 'Red Hotpoint Freezer');
insert into product (part_number, color, brand, category, name) values (509164, 'Red', 'Hotpoint', 'Gas Range', 'Red Hotpoint Gas Range');
insert into product (part_number, color, brand, category, name) values (821189, 'Red', 'Hotpoint', 'Microwave', 'Red Hotpoint Microwave');
insert into product (part_number, color, brand, category, name) values (165611, 'Red', 'Hotpoint', 'Refrigerator', 'Red Hotpoint Refrigerator');
insert into product (part_number, color, brand, category, name) values (775782, 'Red', 'Hotpoint', 'Washer', 'Red Hotpoint Washer');
insert into product (part_number, color, brand, category, name) values (370268, 'Red', 'LG', 'Dishwasher', 'Red LG Dishwasher');
insert into product (part_number, color, brand, category, name) values (929962, 'Red', 'LG', 'Dryer', 'Red LG Dryer');
insert into product (part_number, color, brand, category, name) values (647694, 'Red', 'LG', 'Electric Range', 'Red LG Electric Range');
insert into product (part_number, color, brand, category, name) values (590367, 'Red', 'LG', 'Freezer', 'Red LG Freezer');
insert into product (part_number, color, brand, category, name) values (689586, 'Red', 'LG', 'Gas Range', 'Red LG Gas Range');
insert into product (part_number, color, brand, category, name) values (430368, 'Red', 'LG', 'Microwave', 'Red LG Microwave');
insert into product (part_number, color, brand, category, name) values (431380, 'Red', 'LG', 'Refrigerator', 'Red LG Refrigerator');
insert into product (part_number, color, brand, category, name) values (271649, 'Red', 'LG', 'Washer', 'Red LG Washer');
insert into product (part_number, color, brand, category, name) values (129883, 'Red', 'Miele', 'Dishwasher', 'Red Miele Dishwasher');
insert into product (part_number, color, brand, category, name) values (427398, 'Red', 'Miele', 'Dryer', 'Red Miele Dryer');
insert into product (part_number, color, brand, category, name) values (537759, 'Red', 'Miele', 'Electric Range', 'Red Miele Electric Range');
insert into product (part_number, color, brand, category, name) values (363676, 'Red', 'Miele', 'Freezer', 'Red Miele Freezer');
insert into product (part_number, color, brand, category, name) values (173226, 'Red', 'Miele', 'Gas Range', 'Red Miele Gas Range');
insert into product (part_number, color, brand, category, name) values (174561, 'Red', 'Miele', 'Microwave', 'Red Miele Microwave');
insert into product (part_number, color, brand, category, name) values (351524, 'Red', 'Miele', 'Refrigerator', 'Red Miele Refrigerator');
insert into product (part_number, color, brand, category, name) values (826287, 'Red', 'Miele', 'Washer', 'Red Miele Washer');
insert into product (part_number, color, brand, category, name) values (522938, 'Red', 'Samsung', 'Dishwasher', 'Red Samsung Dishwasher');
insert into product (part_number, color, brand, category, name) values (623056, 'Red', 'Samsung', 'Dryer', 'Red Samsung Dryer');
insert into product (part_number, color, brand, category, name) values (515874, 'Red', 'Samsung', 'Electric Range', 'Red Samsung Electric Range');
insert into product (part_number, color, brand, category, name) values (585077, 'Red', 'Samsung', 'Freezer', 'Red Samsung Freezer');
insert into product (part_number, color, brand, category, name) values (496352, 'Red', 'Samsung', 'Gas Range', 'Red Samsung Gas Range');
insert into product (part_number, color, brand, category, name) values (691136, 'Red', 'Samsung', 'Microwave', 'Red Samsung Microwave');
insert into product (part_number, color, brand, category, name) values (612235, 'Red', 'Samsung', 'Refrigerator', 'Red Samsung Refrigerator');
insert into product (part_number, color, brand, category, name) values (492925, 'Red', 'Samsung', 'Washer', 'Red Samsung Washer');
insert into product (part_number, color, brand, category, name) values (357004, 'Red', 'Subzero', 'Dishwasher', 'Red Subzero Dishwasher');
insert into product (part_number, color, brand, category, name) values (148565, 'Red', 'Subzero', 'Dryer', 'Red Subzero Dryer');
insert into product (part_number, color, brand, category, name) values (827752, 'Red', 'Subzero', 'Electric Range', 'Red Subzero Electric Range');
insert into product (part_number, color, brand, category, name) values (647299, 'Red', 'Subzero', 'Freezer', 'Red Subzero Freezer');
insert into product (part_number, color, brand, category, name) values (524878, 'Red', 'Subzero', 'Gas Range', 'Red Subzero Gas Range');
insert into product (part_number, color, brand, category, name) values (250224, 'Red', 'Subzero', 'Microwave', 'Red Subzero Microwave');
insert into product (part_number, color, brand, category, name) values (681890, 'Red', 'Subzero', 'Refrigerator', 'Red Subzero Refrigerator');
insert into product (part_number, color, brand, category, name) values (661919, 'Red', 'Subzero', 'Washer', 'Red Subzero Washer');
insert into product (part_number, color, brand, category, name) values (631289, 'Blue', 'Amana', 'Dishwasher', 'Blue Amana Dishwasher');
insert into product (part_number, color, brand, category, name) values (539224, 'Blue', 'Amana', 'Dryer', 'Blue Amana Dryer');
insert into product (part_number, color, brand, category, name) values (933885, 'Blue', 'Amana', 'Electric Range', 'Blue Amana Electric Range');
insert into product (part_number, color, brand, category, name) values (462204, 'Blue', 'Amana', 'Freezer', 'Blue Amana Freezer');
insert into product (part_number, color, brand, category, name) values (378367, 'Blue', 'Amana', 'Gas Range', 'Blue Amana Gas Range');
insert into product (part_number, color, brand, category, name) values (738656, 'Blue', 'Amana', 'Microwave', 'Blue Amana Microwave');
insert into product (part_number, color, brand, category, name) values (638477, 'Blue', 'Amana', 'Refrigerator', 'Blue Amana Refrigerator');
insert into product (part_number, color, brand, category, name) values (888685, 'Blue', 'Amana', 'Washer', 'Blue Amana Washer');
insert into product (part_number, color, brand, category, name) values (852585, 'Blue', 'Bosch', 'Dishwasher', 'Blue Bosch Dishwasher');
insert into product (part_number, color, brand, category, name) values (679439, 'Blue', 'Bosch', 'Dryer', 'Blue Bosch Dryer');
insert into product (part_number, color, brand, category, name) values (512835, 'Blue', 'Bosch', 'Electric Range', 'Blue Bosch Electric Range');
insert into product (part_number, color, brand, category, name) values (381815, 'Blue', 'Bosch', 'Freezer', 'Blue Bosch Freezer');
insert into product (part_number, color, brand, category, name) values (653682, 'Blue', 'Bosch', 'Gas Range', 'Blue Bosch Gas Range');
insert into product (part_number, color, brand, category, name) values (170028, 'Blue', 'Bosch', 'Microwave', 'Blue Bosch Microwave');
insert into product (part_number, color, brand, category, name) values (364215, 'Blue', 'Bosch', 'Refrigerator', 'Blue Bosch Refrigerator');
insert into product (part_number, color, brand, category, name) values (606631, 'Blue', 'Bosch', 'Washer', 'Blue Bosch Washer');
insert into product (part_number, color, brand, category, name) values (815464, 'Blue', 'Danby', 'Dishwasher', 'Blue Danby Dishwasher');
insert into product (part_number, color, brand, category, name) values (725304, 'Blue', 'Danby', 'Dryer', 'Blue Danby Dryer');
insert into product (part_number, color, brand, category, name) values (952815, 'Blue', 'Danby', 'Electric Range', 'Blue Danby Electric Range');
insert into product (part_number, color, brand, category, name) values (184571, 'Blue', 'Danby', 'Freezer', 'Blue Danby Freezer');
insert into product (part_number, color, brand, category, name) values (805545, 'Blue', 'Danby', 'Gas Range', 'Blue Danby Gas Range');
insert into product (part_number, color, brand, category, name) values (188605, 'Blue', 'Danby', 'Microwave', 'Blue Danby Microwave');
insert into product (part_number, color, brand, category, name) values (695730, 'Blue', 'Danby', 'Refrigerator', 'Blue Danby Refrigerator');
insert into product (part_number, color, brand, category, name) values (917835, 'Blue', 'Danby', 'Washer', 'Blue Danby Washer');
insert into product (part_number, color, brand, category, name) values (565460, 'Blue', 'Fagor', 'Dishwasher', 'Blue Fagor Dishwasher');
insert into product (part_number, color, brand, category, name) values (676034, 'Blue', 'Fagor', 'Dryer', 'Blue Fagor Dryer');
insert into product (part_number, color, brand, category, name) values (193232, 'Blue', 'Fagor', 'Electric Range', 'Blue Fagor Electric Range');
insert into product (part_number, color, brand, category, name) values (784319, 'Blue', 'Fagor', 'Freezer', 'Blue Fagor Freezer');
insert into product (part_number, color, brand, category, name) values (339002, 'Blue', 'Fagor', 'Gas Range', 'Blue Fagor Gas Range');
insert into product (part_number, color, brand, category, name) values (343852, 'Blue', 'Fagor', 'Microwave', 'Blue Fagor Microwave');
insert into product (part_number, color, brand, category, name) values (578943, 'Blue', 'Fagor', 'Refrigerator', 'Blue Fagor Refrigerator');
insert into product (part_number, color, brand, category, name) values (921322, 'Blue', 'Fagor', 'Washer', 'Blue Fagor Washer');
insert into product (part_number, color, brand, category, name) values (997626, 'Blue', 'Frigidaire', 'Dishwasher', 'Blue Frigidaire Dishwasher');
insert into product (part_number, color, brand, category, name) values (912492, 'Blue', 'Frigidaire', 'Dryer', 'Blue Frigidaire Dryer');
insert into product (part_number, color, brand, category, name) values (139469, 'Blue', 'Frigidaire', 'Electric Range', 'Blue Frigidaire Electric Range');
insert into product (part_number, color, brand, category, name) values (901383, 'Blue', 'Frigidaire', 'Freezer', 'Blue Frigidaire Freezer');
insert into product (part_number, color, brand, category, name) values (629492, 'Blue', 'Frigidaire', 'Gas Range', 'Blue Frigidaire Gas Range');
insert into product (part_number, color, brand, category, name) values (230943, 'Blue', 'Frigidaire', 'Microwave', 'Blue Frigidaire Microwave');
insert into product (part_number, color, brand, category, name) values (369985, 'Blue', 'Frigidaire', 'Refrigerator', 'Blue Frigidaire Refrigerator');
insert into product (part_number, color, brand, category, name) values (822155, 'Blue', 'Frigidaire', 'Washer', 'Blue Frigidaire Washer');
insert into product (part_number, color, brand, category, name) values (761490, 'Blue', 'GE', 'Dishwasher', 'Blue GE Dishwasher');
insert into product (part_number, color, brand, category, name) values (357097, 'Blue', 'GE', 'Dryer', 'Blue GE Dryer');
insert into product (part_number, color, brand, category, name) values (777701, 'Blue', 'GE', 'Electric Range', 'Blue GE Electric Range');
insert into product (part_number, color, brand, category, name) values (349818, 'Blue', 'GE', 'Freezer', 'Blue GE Freezer');
insert into product (part_number, color, brand, category, name) values (312929, 'Blue', 'GE', 'Gas Range', 'Blue GE Gas Range');
insert into product (part_number, color, brand, category, name) values (882108, 'Blue', 'GE', 'Microwave', 'Blue GE Microwave');
insert into product (part_number, color, brand, category, name) values (190007, 'Blue', 'GE', 'Refrigerator', 'Blue GE Refrigerator');
insert into product (part_number, color, brand, category, name) values (682456, 'Blue', 'GE', 'Washer', 'Blue GE Washer');
insert into product (part_number, color, brand, category, name) values (805840, 'Blue', 'Haier', 'Dishwasher', 'Blue Haier Dishwasher');
insert into product (part_number, color, brand, category, name) values (781484, 'Blue', 'Haier', 'Dryer', 'Blue Haier Dryer');
insert into product (part_number, color, brand, category, name) values (988262, 'Blue', 'Haier', 'Electric Range', 'Blue Haier Electric Range');
insert into product (part_number, color, brand, category, name) values (868491, 'Blue', 'Haier', 'Freezer', 'Blue Haier Freezer');
insert into product (part_number, color, brand, category, name) values (263048, 'Blue', 'Haier', 'Gas Range', 'Blue Haier Gas Range');
insert into product (part_number, color, brand, category, name) values (144345, 'Blue', 'Haier', 'Microwave', 'Blue Haier Microwave');
insert into product (part_number, color, brand, category, name) values (861838, 'Blue', 'Haier', 'Refrigerator', 'Blue Haier Refrigerator');
insert into product (part_number, color, brand, category, name) values (516844, 'Blue', 'Haier', 'Washer', 'Blue Haier Washer');
insert into product (part_number, color, brand, category, name) values (648268, 'Blue', 'Hotpoint', 'Dishwasher', 'Blue Hotpoint Dishwasher');
insert into product (part_number, color, brand, category, name) values (337662, 'Blue', 'Hotpoint', 'Dryer', 'Blue Hotpoint Dryer');
insert into product (part_number, color, brand, category, name) values (939157, 'Blue', 'Hotpoint', 'Electric Range', 'Blue Hotpoint Electric Range');
insert into product (part_number, color, brand, category, name) values (496189, 'Blue', 'Hotpoint', 'Freezer', 'Blue Hotpoint Freezer');
insert into product (part_number, color, brand, category, name) values (114526, 'Blue', 'Hotpoint', 'Gas Range', 'Blue Hotpoint Gas Range');
insert into product (part_number, color, brand, category, name) values (435275, 'Blue', 'Hotpoint', 'Microwave', 'Blue Hotpoint Microwave');
insert into product (part_number, color, brand, category, name) values (735424, 'Blue', 'Hotpoint', 'Refrigerator', 'Blue Hotpoint Refrigerator');
insert into product (part_number, color, brand, category, name) values (301712, 'Blue', 'Hotpoint', 'Washer', 'Blue Hotpoint Washer');
insert into product (part_number, color, brand, category, name) values (767340, 'Blue', 'LG', 'Dishwasher', 'Blue LG Dishwasher');
insert into product (part_number, color, brand, category, name) values (214774, 'Blue', 'LG', 'Dryer', 'Blue LG Dryer');
insert into product (part_number, color, brand, category, name) values (551766, 'Blue', 'LG', 'Electric Range', 'Blue LG Electric Range');
insert into product (part_number, color, brand, category, name) values (269893, 'Blue', 'LG', 'Freezer', 'Blue LG Freezer');
insert into product (part_number, color, brand, category, name) values (852276, 'Blue', 'LG', 'Gas Range', 'Blue LG Gas Range');
insert into product (part_number, color, brand, category, name) values (565586, 'Blue', 'LG', 'Microwave', 'Blue LG Microwave');
insert into product (part_number, color, brand, category, name) values (230679, 'Blue', 'LG', 'Refrigerator', 'Blue LG Refrigerator');
insert into product (part_number, color, brand, category, name) values (883751, 'Blue', 'LG', 'Washer', 'Blue LG Washer');
insert into product (part_number, color, brand, category, name) values (267594, 'Blue', 'Miele', 'Dishwasher', 'Blue Miele Dishwasher');
insert into product (part_number, color, brand, category, name) values (600471, 'Blue', 'Miele', 'Dryer', 'Blue Miele Dryer');
insert into product (part_number, color, brand, category, name) values (384828, 'Blue', 'Miele', 'Electric Range', 'Blue Miele Electric Range');
insert into product (part_number, color, brand, category, name) values (842026, 'Blue', 'Miele', 'Freezer', 'Blue Miele Freezer');
insert into product (part_number, color, brand, category, name) values (539589, 'Blue', 'Miele', 'Gas Range', 'Blue Miele Gas Range');
insert into product (part_number, color, brand, category, name) values (909700, 'Blue', 'Miele', 'Microwave', 'Blue Miele Microwave');
insert into product (part_number, color, brand, category, name) values (647861, 'Blue', 'Miele', 'Refrigerator', 'Blue Miele Refrigerator');
insert into product (part_number, color, brand, category, name) values (867127, 'Blue', 'Miele', 'Washer', 'Blue Miele Washer');
insert into product (part_number, color, brand, category, name) values (398621, 'Blue', 'Samsung', 'Dishwasher', 'Blue Samsung Dishwasher');
insert into product (part_number, color, brand, category, name) values (952659, 'Blue', 'Samsung', 'Dryer', 'Blue Samsung Dryer');
insert into product (part_number, color, brand, category, name) values (129048, 'Blue', 'Samsung', 'Electric Range', 'Blue Samsung Electric Range');
insert into product (part_number, color, brand, category, name) values (217752, 'Blue', 'Samsung', 'Freezer', 'Blue Samsung Freezer');
insert into product (part_number, color, brand, category, name) values (553402, 'Blue', 'Samsung', 'Gas Range', 'Blue Samsung Gas Range');
insert into product (part_number, color, brand, category, name) values (141515, 'Blue', 'Samsung', 'Microwave', 'Blue Samsung Microwave');
insert into product (part_number, color, brand, category, name) values (792444, 'Blue', 'Samsung', 'Refrigerator', 'Blue Samsung Refrigerator');
insert into product (part_number, color, brand, category, name) values (258006, 'Blue', 'Samsung', 'Washer', 'Blue Samsung Washer');
insert into product (part_number, color, brand, category, name) values (771473, 'Blue', 'Subzero', 'Dishwasher', 'Blue Subzero Dishwasher');
insert into product (part_number, color, brand, category, name) values (580976, 'Blue', 'Subzero', 'Dryer', 'Blue Subzero Dryer');
insert into product (part_number, color, brand, category, name) values (963262, 'Blue', 'Subzero', 'Electric Range', 'Blue Subzero Electric Range');
insert into product (part_number, color, brand, category, name) values (399699, 'Blue', 'Subzero', 'Freezer', 'Blue Subzero Freezer');
insert into product (part_number, color, brand, category, name) values (793363, 'Blue', 'Subzero', 'Gas Range', 'Blue Subzero Gas Range');
insert into product (part_number, color, brand, category, name) values (977671, 'Blue', 'Subzero', 'Microwave', 'Blue Subzero Microwave');
insert into product (part_number, color, brand, category, name) values (570612, 'Blue', 'Subzero', 'Refrigerator', 'Blue Subzero Refrigerator');
insert into product (part_number, color, brand, category, name) values (925609, 'Blue', 'Subzero', 'Washer', 'Blue Subzero Washer');
insert into product (part_number, color, brand, category, name) values (244994, 'Silver', 'Amana', 'Dishwasher', 'Silver Amana Dishwasher');
insert into product (part_number, color, brand, category, name) values (796111, 'Silver', 'Amana', 'Dryer', 'Silver Amana Dryer');
insert into product (part_number, color, brand, category, name) values (813244, 'Silver', 'Amana', 'Electric Range', 'Silver Amana Electric Range');
insert into product (part_number, color, brand, category, name) values (678102, 'Silver', 'Amana', 'Freezer', 'Silver Amana Freezer');
insert into product (part_number, color, brand, category, name) values (217827, 'Silver', 'Amana', 'Gas Range', 'Silver Amana Gas Range');
insert into product (part_number, color, brand, category, name) values (678953, 'Silver', 'Amana', 'Microwave', 'Silver Amana Microwave');
insert into product (part_number, color, brand, category, name) values (141912, 'Silver', 'Amana', 'Refrigerator', 'Silver Amana Refrigerator');
insert into product (part_number, color, brand, category, name) values (531346, 'Silver', 'Amana', 'Washer', 'Silver Amana Washer');
insert into product (part_number, color, brand, category, name) values (375674, 'Silver', 'Bosch', 'Dishwasher', 'Silver Bosch Dishwasher');
insert into product (part_number, color, brand, category, name) values (483766, 'Silver', 'Bosch', 'Dryer', 'Silver Bosch Dryer');
insert into product (part_number, color, brand, category, name) values (978200, 'Silver', 'Bosch', 'Electric Range', 'Silver Bosch Electric Range');
insert into product (part_number, color, brand, category, name) values (847601, 'Silver', 'Bosch', 'Freezer', 'Silver Bosch Freezer');
insert into product (part_number, color, brand, category, name) values (348310, 'Silver', 'Bosch', 'Gas Range', 'Silver Bosch Gas Range');
insert into product (part_number, color, brand, category, name) values (261155, 'Silver', 'Bosch', 'Microwave', 'Silver Bosch Microwave');
insert into product (part_number, color, brand, category, name) values (745346, 'Silver', 'Bosch', 'Refrigerator', 'Silver Bosch Refrigerator');
insert into product (part_number, color, brand, category, name) values (631767, 'Silver', 'Bosch', 'Washer', 'Silver Bosch Washer');
insert into product (part_number, color, brand, category, name) values (956204, 'Silver', 'Danby', 'Dishwasher', 'Silver Danby Dishwasher');
insert into product (part_number, color, brand, category, name) values (857908, 'Silver', 'Danby', 'Dryer', 'Silver Danby Dryer');
insert into product (part_number, color, brand, category, name) values (580857, 'Silver', 'Danby', 'Electric Range', 'Silver Danby Electric Range');
insert into product (part_number, color, brand, category, name) values (785604, 'Silver', 'Danby', 'Freezer', 'Silver Danby Freezer');
insert into product (part_number, color, brand, category, name) values (214827, 'Silver', 'Danby', 'Gas Range', 'Silver Danby Gas Range');
insert into product (part_number, color, brand, category, name) values (696947, 'Silver', 'Danby', 'Microwave', 'Silver Danby Microwave');
insert into product (part_number, color, brand, category, name) values (228890, 'Silver', 'Danby', 'Refrigerator', 'Silver Danby Refrigerator');
insert into product (part_number, color, brand, category, name) values (970656, 'Silver', 'Danby', 'Washer', 'Silver Danby Washer');
insert into product (part_number, color, brand, category, name) values (690451, 'Silver', 'Fagor', 'Dishwasher', 'Silver Fagor Dishwasher');
insert into product (part_number, color, brand, category, name) values (399200, 'Silver', 'Fagor', 'Dryer', 'Silver Fagor Dryer');
insert into product (part_number, color, brand, category, name) values (118130, 'Silver', 'Fagor', 'Electric Range', 'Silver Fagor Electric Range');
insert into product (part_number, color, brand, category, name) values (565924, 'Silver', 'Fagor', 'Freezer', 'Silver Fagor Freezer');
insert into product (part_number, color, brand, category, name) values (303135, 'Silver', 'Fagor', 'Gas Range', 'Silver Fagor Gas Range');
insert into product (part_number, color, brand, category, name) values (751681, 'Silver', 'Fagor', 'Microwave', 'Silver Fagor Microwave');
insert into product (part_number, color, brand, category, name) values (765146, 'Silver', 'Fagor', 'Refrigerator', 'Silver Fagor Refrigerator');
insert into product (part_number, color, brand, category, name) values (116684, 'Silver', 'Fagor', 'Washer', 'Silver Fagor Washer');
insert into product (part_number, color, brand, category, name) values (399472, 'Silver', 'Frigidaire', 'Dishwasher', 'Silver Frigidaire Dishwasher');
insert into product (part_number, color, brand, category, name) values (423503, 'Silver', 'Frigidaire', 'Dryer', 'Silver Frigidaire Dryer');
insert into product (part_number, color, brand, category, name) values (934943, 'Silver', 'Frigidaire', 'Electric Range', 'Silver Frigidaire Electric Range');
insert into product (part_number, color, brand, category, name) values (243084, 'Silver', 'Frigidaire', 'Freezer', 'Silver Frigidaire Freezer');
insert into product (part_number, color, brand, category, name) values (825538, 'Silver', 'Frigidaire', 'Gas Range', 'Silver Frigidaire Gas Range');
insert into product (part_number, color, brand, category, name) values (497190, 'Silver', 'Frigidaire', 'Microwave', 'Silver Frigidaire Microwave');
insert into product (part_number, color, brand, category, name) values (582813, 'Silver', 'Frigidaire', 'Refrigerator', 'Silver Frigidaire Refrigerator');
insert into product (part_number, color, brand, category, name) values (111368, 'Silver', 'Frigidaire', 'Washer', 'Silver Frigidaire Washer');
insert into product (part_number, color, brand, category, name) values (631808, 'Silver', 'GE', 'Dishwasher', 'Silver GE Dishwasher');
insert into product (part_number, color, brand, category, name) values (192726, 'Silver', 'GE', 'Dryer', 'Silver GE Dryer');
insert into product (part_number, color, brand, category, name) values (626042, 'Silver', 'GE', 'Electric Range', 'Silver GE Electric Range');
insert into product (part_number, color, brand, category, name) values (489955, 'Silver', 'GE', 'Freezer', 'Silver GE Freezer');
insert into product (part_number, color, brand, category, name) values (921129, 'Silver', 'GE', 'Gas Range', 'Silver GE Gas Range');
insert into product (part_number, color, brand, category, name) values (621058, 'Silver', 'GE', 'Microwave', 'Silver GE Microwave');
insert into product (part_number, color, brand, category, name) values (826699, 'Silver', 'GE', 'Refrigerator', 'Silver GE Refrigerator');
insert into product (part_number, color, brand, category, name) values (376461, 'Silver', 'GE', 'Washer', 'Silver GE Washer');
insert into product (part_number, color, brand, category, name) values (715356, 'Silver', 'Haier', 'Dishwasher', 'Silver Haier Dishwasher');
insert into product (part_number, color, brand, category, name) values (518840, 'Silver', 'Haier', 'Dryer', 'Silver Haier Dryer');
insert into product (part_number, color, brand, category, name) values (793861, 'Silver', 'Haier', 'Electric Range', 'Silver Haier Electric Range');
insert into product (part_number, color, brand, category, name) values (491229, 'Silver', 'Haier', 'Freezer', 'Silver Haier Freezer');
insert into product (part_number, color, brand, category, name) values (138200, 'Silver', 'Haier', 'Gas Range', 'Silver Haier Gas Range');
insert into product (part_number, color, brand, category, name) values (686560, 'Silver', 'Haier', 'Microwave', 'Silver Haier Microwave');
insert into product (part_number, color, brand, category, name) values (705192, 'Silver', 'Haier', 'Refrigerator', 'Silver Haier Refrigerator');
insert into product (part_number, color, brand, category, name) values (609966, 'Silver', 'Haier', 'Washer', 'Silver Haier Washer');
insert into product (part_number, color, brand, category, name) values (140654, 'Silver', 'Hotpoint', 'Dishwasher', 'Silver Hotpoint Dishwasher');
insert into product (part_number, color, brand, category, name) values (183727, 'Silver', 'Hotpoint', 'Dryer', 'Silver Hotpoint Dryer');
insert into product (part_number, color, brand, category, name) values (483744, 'Silver', 'Hotpoint', 'Electric Range', 'Silver Hotpoint Electric Range');
insert into product (part_number, color, brand, category, name) values (372322, 'Silver', 'Hotpoint', 'Freezer', 'Silver Hotpoint Freezer');
insert into product (part_number, color, brand, category, name) values (951606, 'Silver', 'Hotpoint', 'Gas Range', 'Silver Hotpoint Gas Range');
insert into product (part_number, color, brand, category, name) values (991921, 'Silver', 'Hotpoint', 'Microwave', 'Silver Hotpoint Microwave');
insert into product (part_number, color, brand, category, name) values (179080, 'Silver', 'Hotpoint', 'Refrigerator', 'Silver Hotpoint Refrigerator');
insert into product (part_number, color, brand, category, name) values (423707, 'Silver', 'Hotpoint', 'Washer', 'Silver Hotpoint Washer');
insert into product (part_number, color, brand, category, name) values (800135, 'Silver', 'LG', 'Dishwasher', 'Silver LG Dishwasher');
insert into product (part_number, color, brand, category, name) values (194744, 'Silver', 'LG', 'Dryer', 'Silver LG Dryer');
insert into product (part_number, color, brand, category, name) values (851055, 'Silver', 'LG', 'Electric Range', 'Silver LG Electric Range');
insert into product (part_number, color, brand, category, name) values (212000, 'Silver', 'LG', 'Freezer', 'Silver LG Freezer');
insert into product (part_number, color, brand, category, name) values (988555, 'Silver', 'LG', 'Gas Range', 'Silver LG Gas Range');
insert into product (part_number, color, brand, category, name) values (305792, 'Silver', 'LG', 'Microwave', 'Silver LG Microwave');
insert into product (part_number, color, brand, category, name) values (506706, 'Silver', 'LG', 'Refrigerator', 'Silver LG Refrigerator');
insert into product (part_number, color, brand, category, name) values (529833, 'Silver', 'LG', 'Washer', 'Silver LG Washer');
insert into product (part_number, color, brand, category, name) values (973459, 'Silver', 'Miele', 'Dishwasher', 'Silver Miele Dishwasher');
insert into product (part_number, color, brand, category, name) values (225110, 'Silver', 'Miele', 'Dryer', 'Silver Miele Dryer');
insert into product (part_number, color, brand, category, name) values (744581, 'Silver', 'Miele', 'Electric Range', 'Silver Miele Electric Range');
insert into product (part_number, color, brand, category, name) values (321572, 'Silver', 'Miele', 'Freezer', 'Silver Miele Freezer');
insert into product (part_number, color, brand, category, name) values (434350, 'Silver', 'Miele', 'Gas Range', 'Silver Miele Gas Range');
insert into product (part_number, color, brand, category, name) values (170953, 'Silver', 'Miele', 'Microwave', 'Silver Miele Microwave');
insert into product (part_number, color, brand, category, name) values (494287, 'Silver', 'Miele', 'Refrigerator', 'Silver Miele Refrigerator');
insert into product (part_number, color, brand, category, name) values (277331, 'Silver', 'Miele', 'Washer', 'Silver Miele Washer');
insert into product (part_number, color, brand, category, name) values (750905, 'Silver', 'Samsung', 'Dishwasher', 'Silver Samsung Dishwasher');
insert into product (part_number, color, brand, category, name) values (822736, 'Silver', 'Samsung', 'Dryer', 'Silver Samsung Dryer');
insert into product (part_number, color, brand, category, name) values (457679, 'Silver', 'Samsung', 'Electric Range', 'Silver Samsung Electric Range');
insert into product (part_number, color, brand, category, name) values (977165, 'Silver', 'Samsung', 'Freezer', 'Silver Samsung Freezer');
insert into product (part_number, color, brand, category, name) values (474930, 'Silver', 'Samsung', 'Gas Range', 'Silver Samsung Gas Range');
insert into product (part_number, color, brand, category, name) values (214343, 'Silver', 'Samsung', 'Microwave', 'Silver Samsung Microwave');
insert into product (part_number, color, brand, category, name) values (978963, 'Silver', 'Samsung', 'Refrigerator', 'Silver Samsung Refrigerator');
insert into product (part_number, color, brand, category, name) values (690001, 'Silver', 'Samsung', 'Washer', 'Silver Samsung Washer');
insert into product (part_number, color, brand, category, name) values (735019, 'Silver', 'Subzero', 'Dishwasher', 'Silver Subzero Dishwasher');
insert into product (part_number, color, brand, category, name) values (390494, 'Silver', 'Subzero', 'Dryer', 'Silver Subzero Dryer');
insert into product (part_number, color, brand, category, name) values (258591, 'Silver', 'Subzero', 'Electric Range', 'Silver Subzero Electric Range');
insert into product (part_number, color, brand, category, name) values (387414, 'Silver', 'Subzero', 'Freezer', 'Silver Subzero Freezer');
insert into product (part_number, color, brand, category, name) values (131004, 'Silver', 'Subzero', 'Gas Range', 'Silver Subzero Gas Range');
insert into product (part_number, color, brand, category, name) values (205143, 'Silver', 'Subzero', 'Microwave', 'Silver Subzero Microwave');
insert into product (part_number, color, brand, category, name) values (703424, 'Silver', 'Subzero', 'Refrigerator', 'Silver Subzero Refrigerator');
insert into product (part_number, color, brand, category, name) values (806461, 'Silver', 'Subzero', 'Washer', 'Silver Subzero Washer');
insert into product (part_number, color, brand, category, name) values (292127, 'Metallic', 'Amana', 'Dishwasher', 'Metallic Amana Dishwasher');
insert into product (part_number, color, brand, category, name) values (459338, 'Metallic', 'Amana', 'Dryer', 'Metallic Amana Dryer');
insert into product (part_number, color, brand, category, name) values (909264, 'Metallic', 'Amana', 'Electric Range', 'Metallic Amana Electric Range');
insert into product (part_number, color, brand, category, name) values (168039, 'Metallic', 'Amana', 'Freezer', 'Metallic Amana Freezer');
insert into product (part_number, color, brand, category, name) values (710506, 'Metallic', 'Amana', 'Gas Range', 'Metallic Amana Gas Range');
insert into product (part_number, color, brand, category, name) values (936922, 'Metallic', 'Amana', 'Microwave', 'Metallic Amana Microwave');
insert into product (part_number, color, brand, category, name) values (353283, 'Metallic', 'Amana', 'Refrigerator', 'Metallic Amana Refrigerator');
insert into product (part_number, color, brand, category, name) values (470717, 'Metallic', 'Amana', 'Washer', 'Metallic Amana Washer');
insert into product (part_number, color, brand, category, name) values (630870, 'Metallic', 'Bosch', 'Dishwasher', 'Metallic Bosch Dishwasher');
insert into product (part_number, color, brand, category, name) values (688082, 'Metallic', 'Bosch', 'Dryer', 'Metallic Bosch Dryer');
insert into product (part_number, color, brand, category, name) values (507894, 'Metallic', 'Bosch', 'Electric Range', 'Metallic Bosch Electric Range');
insert into product (part_number, color, brand, category, name) values (407109, 'Metallic', 'Bosch', 'Freezer', 'Metallic Bosch Freezer');
insert into product (part_number, color, brand, category, name) values (877540, 'Metallic', 'Bosch', 'Gas Range', 'Metallic Bosch Gas Range');
insert into product (part_number, color, brand, category, name) values (907632, 'Metallic', 'Bosch', 'Microwave', 'Metallic Bosch Microwave');
insert into product (part_number, color, brand, category, name) values (863489, 'Metallic', 'Bosch', 'Refrigerator', 'Metallic Bosch Refrigerator');
insert into product (part_number, color, brand, category, name) values (508521, 'Metallic', 'Bosch', 'Washer', 'Metallic Bosch Washer');
insert into product (part_number, color, brand, category, name) values (756551, 'Metallic', 'Danby', 'Dishwasher', 'Metallic Danby Dishwasher');
insert into product (part_number, color, brand, category, name) values (720060, 'Metallic', 'Danby', 'Dryer', 'Metallic Danby Dryer');
insert into product (part_number, color, brand, category, name) values (556937, 'Metallic', 'Danby', 'Electric Range', 'Metallic Danby Electric Range');
insert into product (part_number, color, brand, category, name) values (376739, 'Metallic', 'Danby', 'Freezer', 'Metallic Danby Freezer');
